let items = [
    {
        id: "product-1",
        name: "Sibaristica",
        desc: "Bönor från Guatemala och Colombia",
        price: 129,
        img: "img/produkt-1-kaffepasar.jpg",
    },
    {
        id: "product-2",
        name: "Blue Magic",
        desc: "Espressobönor",
        price: 119,
        img: "img/produkt-2-andrakaffapasar.jpg",
    },
    {
        id: "product-3",
        name: "Specialty Beans",
        desc: "Speciella bönor från Ethiopien",
        price: 129,
        img: "img/produkt-3-merkaffe.jpg",
    },
    {
        id: "product-4",
        name: "Rustik",
        desc: "Svart kopp i keramik",
        price: 49,
        img: "img/produkt-4-kopp.jpg",
    },
    {
        id: "product-5",
        name: "Grön",
        desc: "Kopp i poppande grön färg",
        price: 39,
        img: "img/produkt-5-kopp2.jpg",
    },
    {
        id: "product-6",
        name: "V60",
        desc: "V60 bryggaren som tilltalar din inre hipster",
        price: 599,
        img: "img/produkt-6-v60.jpg",
    },
    {
        id: "product-7",
        name: "Aeropress",
        desc: "För dig som vill kunna göra kaffe var som helst!",
        price: 499,
        img: "img/produkt-7-aeropress.jpg",
    },
    {
        id: "product-8",
        name: "Fancy",
        desc: "För ditt finbesök",
        price: 49,
        img: "img/produkt-8-kopp3.jpg",
    },
    {
        id: "product-9",
        name: "Franskpress",
        desc: "Den klassiska Franskpressen går alltid hem",
        price: 199,
        img: "img/produkt-9-franskpress.jpg",
    },
    {
        id: "product10",
        name: "Orange",
        desc: "En större kopp för dig med ett större beroende",
        price: 39,
        img: "img/produkt-10-kopp4.jpg",
    },
  ];